"use client"
// import type {Metadata} from "next";
import {DM_Serif_Text,Griffy,Outfit} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {Toaster} from "sonner";
import {CartProvider} from "react-use-cart";

const griffy = Griffy({
  weight: ['400'],
  variable: "--font-griffy-serif",
  subsets: ["latin"],
})

const dm_serif = DM_Serif_Text({
  weight: ["400"],
  variable: "--font-dm-serif",
  subsets: ["latin"],

})

const outfit = Outfit({
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true"
        className={`${outfit.className} ${griffy.variable} ${dm_serif.variable} antialiased`}
      >
        <CartProvider id="product">
          <Navbar />
          {children}
          <Toaster />
        </CartProvider>
      </body>
    </html>
  );
}
